FROM openjdk:8-jdk-alpine
COPY ./target/medical-representative-schedule-service-0.0.1-SNAPSHOT.jar medical-representative-schedule-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","medical-representative-schedule-service-0.0.1-SNAPSHOT.jar"]