FROM openjdk:8-jdk-alpine
COPY ./target/Medicine-Stock-MicroService-0.0.1-SNAPSHOT.jar Medicine-Stock-MicroService-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","Medicine-Stock-MicroService-0.0.1-SNAPSHOT.jar"]